export const stateCityData = {
  "AK": ["Anchorage"],
  "AL": [
    "Auburn",
    "Birmingham",
    "Decatur",
    "Dothan",
    "Florence",
    "Gadsden",
    "Hoover",
    "Huntsville",
    "Madison",
    "Mobile",
    "Montgomery",
    "Tuscaloosa"
  ],
  "AR": [
    "Bentonville",
    "Conway",
    "Fayetteville",
    "Fort Smith",
    "Jonesboro",
    "Little Rock",
    "North Little Rock",
    "Pine Bluff",
    "Rogers",
    "Springdale"
  ],
  "AZ": [
    "Apache Junction",
    "Avondale",
    "Buckeye",
    "Bullhead City",
    "Casa Grande",
    "Chandler",
    "Flagstaff",
    "Gilbert",
    "Glendale",
    "Goodyear",
    "Lake Havasu City",
    "Marana",
    "Maricopa",
    "Mesa",
    "Oro Valley",
    "Peoria",
    "Phoenix",
    "Prescott",
    "Prescott Valley",
    "Scottsdale",
    "Sierra Vista",
    "Surprise",
    "Tempe",
    "Tucson",
    "Yuma"
  ],
  "CA": [
    "Anaheim",
    "Bakersfield",
    "Berkeley",
    "Burbank",
    "Carlsbad",
    "Chula Vista",
    "Concord",
    "Corona",
    "Costa Mesa",
    "Daly City",
    "Downey",
    "El Cajon",
    "El Monte",
    "Escondido",
    "Fairfield",
    "Fontana",
    "Fremont",
    "Fresno",
    "Fullerton",
    "Garden Grove",
    "Glendale",
    "Hayward",
    "Huntington Beach",
    "Inglewood",
    "Irvine",
    "Lancaster",
    "Long Beach",
    "Los Angeles",
    "Modesto",
    "Moreno Valley",
    "Murrieta",
    "Norwalk",
    "Oakland",
    "Oceanside",
    "Ontario",
    "Orange",
    "Oxnard",
    "Palmdale",
    "Pasadena",
    "Pomona",
    "Rancho Cucamonga",
    "Redding",
    "Rialto",
    "Richmond",
    "Riverside",
    "Roseville",
    "Sacramento",
    "Salinas",
    "San Bernardino",
    "San Buenaventura (Ventura)",
    "San Diego",
    "San Francisco",
    "San Jose",
    "San Mateo",
    "Santa Ana",
    "Santa Barbara",
    "Santa Clara",
    "Santa Clarita",
    "Santa Maria",
    "Santa Monica",
    "Santa Rosa",
    "Simi Valley",
    "Stockton",
    "Sunnyvale",
    "Temecula",
    "Thousand Oaks",
    "Torrance",
    "Vallejo",
    "Visalia",
    "Vista",
    "West Covina",
    "Westminster"
  ],
  "CO": [
    "Arvada",
    "Aurora",
    "Boulder",
    "Broomfield",
    "Castle Rock",
    "Centennial",
    "Colorado Springs",
    "Commerce City",
    "Denver",
    "Fort Collins",
    "Grand Junction",
    "Greeley",
    "Lakewood",
    "Littleton",
    "Longmont",
    "Loveland",
    "Northglenn",
    "Parker",
    "Pueblo",
    "Thornton",
    "Westminster"
  ],
  "CT": [
    "Bridgeport",
    "Bristol",
    "Danbury",
    "Hartford",
    "Meriden",
    "Middletown",
    "Milford",
    "New Britain",
    "New Haven",
    "Norwalk",
    "Norwich",
    "Shelton",
    "Stamford",
    "Waterbury",
    "West Haven"
  ],
  "DC": ["Washington"],
  "DE": ["Dover", "Wilmington"],
  "FL": [
    "Apopka",
    "Aventura",
    "Boca Raton",
    "Bonita Springs",
    "Boynton Beach",
    "Bradenton",
    "Cape Coral",
    "Clearwater",
    "Coconut Creek",
    "Coral Gables",
    "Coral Springs",
    "Cutler Bay",
    "Davie",
    "Daytona Beach",
    "Deerfield Beach",
    "Delray Beach",
    "Deltona",
    "Doral",
    "Dunwoody",
    "Fort Lauderdale",
    "Fort Myers",
    "Gainesville",
    "Greenacres",
    "Hialeah",
    "Hollywood",
    "Homestead",
    "Jacksonville",
    "Jupiter",
    "Kissimmee",
    "Lakeland",
    "Largo",
    "Lauderhill",
    "Margate",
    "Melbourne",
    "Miami",
    "Miami Beach",
    "Miami Gardens",
    "Miramar",
    "North Miami",
    "North Port",
    "Oakland Park",
    "Ocala",
    "Orlando",
    "Palm Bay",
    "Palm Coast",
    "Palm Springs",
    "Palmetto Bay",
    "Pembroke Pines",
    "Pensacola",
    "Pinecrest",
    "Pinellas Park",
    "Plantation",
    "Pompano Beach",
    "Port Orange",
    "Port St. Lucie",
    "Riviera Beach",
    "Sanford",
    "Sarasota",
    "St. Petersburg",
    "Sunrise",
    "Tallahassee",
    "Tamarac",
    "Tampa",
    "Titusville",
    "Wellington",
    "West Palm Beach",
    "Weston",
    "Winter Garden",
    "Winter Haven",
    "Winter Springs"
  ],
  "GA": [
    "Albany",
    "Alpharetta",
    "Athens",
    "Atlanta",
    "Augusta",
    "Columbus",
    "Decatur",
    "Douglasville",
    "Duluth",
    "Dunwoody",
    "East Point",
    "Gainesville",
    "Johns Creek",
    "Kennesaw",
    "Macon",
    "Marietta",
    "Newnan",
    "Peachtree City",
    "Rome",
    "Roswell",
    "Sandy Springs",
    "Savannah",
    "Smyrna",
    "Valdosta",
    "Warner Robins"
  ],
  "HI": ["Honolulu"],
  "IA": [
    "Ames",
    "Ankeny",
    "Cedar Falls",
    "Cedar Rapids",
    "Council Bluffs",
    "Davenport",
    "Des Moines",
    "Dubuque",
    "Iowa City",
    "Marion",
    "Marshalltown",
    "Mason City",
    "Sioux City",
    "Urbandale",
    "Waterloo",
    "West Des Moines"
  ],
  "ID": [
    "Boise",
    "Caldwell",
    "Coeur d'Alene",
    "Idaho Falls",
    "Lewiston",
    "Meridian",
    "Nampa",
    "Pocatello",
    "Post Falls",
    "Twin Falls"
  ],
  "IL": [
    "Aurora",
    "Bloomington",
    "Champaign",
    "Chicago",
    "Cicero",
    "Decatur",
    "Elgin",
    "Evanston",
    "Joliet",
    "Naperville",
    "Peoria",
    "Rockford",
    "Schaumburg",
    "Springfield",
    "Waukegan"
  ],
  "IN": [
    "Anderson",
    "Bloomington",
    "Carmel",
    "Elkhart",
    "Evansville",
    "Fishers",
    "Fort Wayne",
    "Gary",
    "Hammond",
    "Indianapolis",
    "Jeffersonville",
    "Kokomo",
    "Lafayette",
    "Muncie",
    "Noblesville",
    "South Bend",
    "Terre Haute"
  ],
  "KS": [
    "Kansas City",
    "Lawrence",
    "Lenexa",
    "Manhattan",
    "Olathe",
    "Overland Park",
    "Salina",
    "Shawnee",
    "Topeka",
    "Wichita"
  ],
  "KY": [
    "Bowling Green",
    "Covington",
    "Frankfort",
    "Henderson",
    "Lexington",
    "Louisville",
    "Owensboro",
    "Paducah",
    "Richmond"
  ],
  "LA": [
    "Alexandria",
    "Baton Rouge",
    "Bossier City",
    "Lafayette",
    "Lake Charles",
    "Monroe",
    "New Orleans",
    "Shreveport"
  ],
  "MA": [
    "Boston",
    "Brockton",
    "Cambridge",
    "Fall River",
    "Lowell",
    "Lynn",
    "New Bedford",
    "Quincy",
    "Somerville",
    "Springfield",
    "Worcester"
  ],
  "MD": [
    "Annapolis",
    "Baltimore",
    "Bethesda",
    "Bowie",
    "College Park",
    "Columbia",
    "Frederick",
    "Gaithersburg",
    "Germantown",
    "Hagerstown",
    "Laurel",
    "Rockville",
    "Salisbury",
    "Silver Spring",
    "Waldorf"
  ],
  "ME": [
    "Auburn",
    "Augusta",
    "Bangor",
    "Biddeford",
    "Brunswick",
    "Lewiston",
    "Portland",
    "Saco",
    "South Portland",
    "Waterville",
    "Westbrook"
  ],
  "MI": [
    "Ann Arbor",
    "Battle Creek",
    "Dearborn",
    "Detroit",
    "Farmington Hills",
    "Flint",
    "Grand Rapids",
    "Kalamazoo",
    "Lansing",
    "Livonia",
    "Novi",
    "Pontiac",
    "Rochester Hills",
    "Royal Oak",
    "Saginaw",
    "Southfield",
    "Sterling Heights",
    "Troy",
    "Warren",
    "Westland"
  ],
  "MN": [
    "Bloomington",
    "Brooklyn Park",
    "Burnsville",
    "Coon Rapids",
    "Duluth",
    "Eagan",
    "Eden Prairie",
    "Lakeville",
    "Mankato",
    "Maple Grove",
    "Minneapolis",
    "Minnetonka",
    "Plymouth",
    "Rochester",
    "St. Cloud",
    "St. Paul",
    "Woodbury"
  ],
  "MO": [
    "Blue Springs",
    "Cape Girardeau",
    "Chesterfield",
    "Columbia",
    "Florissant",
    "Independence",
    "Jefferson City",
    "Joplin",
    "Kansas City",
    "Lee's Summit",
    "O'Fallon",
    "Springfield",
    "St. Charles",
    "St. Joseph",
    "St. Louis",
    "St. Peters"
  ],
  "MS": [
    "Biloxi",
    "Gulfport",
    "Hattiesburg",
    "Jackson",
    "Meridian",
    "Olive Branch",
    "Southaven",
    "Tupelo"
  ],
  "MT": [
    "Billings",
    "Bozeman",
    "Butte",
    "Great Falls",
    "Helena",
    "Kalispell",
    "Missoula"
  ],
  "NC": [
    "Asheville",
    "Burlington",
    "Cary",
    "Chapel Hill",
    "Charlotte",
    "Concord",
    "Durham",
    "Fayetteville",
    "Gastonia",
    "Greensboro",
    "Greenville",
    "High Point",
    "Jacksonville",
    "Raleigh",
    "Rocky Mount",
    "Wilmington",
    "Wilson",
    "Winston-Salem"
  ],
  "ND": ["Bismarck", "Fargo", "Grand Forks", "Minot"],
  "NE": [
    "Bellevue",
    "Grand Island",
    "Kearney",
    "Lincoln",
    "Omaha"
  ],
  "NH": [
    "Concord",
    "Dover",
    "Manchester",
    "Nashua",
    "Rochester"
  ],
  "NJ": [
    "Atlantic City",
    "Bayonne",
    "Camden",
    "Clifton",
    "East Orange",
    "Elizabeth",
    "Hackensack",
    "Hoboken",
    "Jersey City",
    "Linden",
    "New Brunswick",
    "Newark",
    "Passaic",
    "Paterson",
    "Perth Amboy",
    "Plainfield",
    "Sayreville",
    "Trenton",
    "Union City",
    "Vineland"
  ],
  "NM": [
    "Alamogordo",
    "Albuquerque",
    "Carlsbad",
    "Clovis",
    "Farmington",
    "Hobbs",
    "Las Cruces",
    "Rio Rancho",
    "Roswell",
    "Santa Fe"
  ],
  "NV": [
    "Carson City",
    "Henderson",
    "Las Vegas",
    "North Las Vegas",
    "Reno",
    "Sparks"
  ],
  "NY": [
    "Albany",
    "Binghamton",
    "Buffalo",
    "Freeport",
    "Hempstead",
    "Mount Vernon",
    "New Rochelle",
    "New York",
    "Niagara Falls",
    "Rochester",
    "Schenectady",
    "Syracuse",
    "Troy",
    "Utica",
    "Valley Stream",
    "White Plains",
    "Yonkers"
  ],
  "OH": [
    "Akron",
    "Beavercreek",
    "Canton",
    "Cincinnati",
    "Cleveland",
    "Cleveland Heights",
    "Columbus",
    "Cuyahoga Falls",
    "Dayton",
    "Dublin",
    "Elyria",
    "Euclid",
    "Fairfield",
    "Findlay",
    "Hamilton",
    "Huber Heights",
    "Kettering",
    "Lakewood",
    "Lancaster",
    "Lima",
    "Lorain",
    "Mansfield",
    "Marion",
    "Mentor",
    "Middletown",
    "Newark",
    "Parma",
    "Springfield",
    "Strongsville",
    "Toledo",
    "Warren",
    "Westerville",
    "Youngstown"
  ],
  "OK": [
    "Broken Arrow",
    "Edmond",
    "Enid",
    "Lawton",
    "Midwest City",
    "Moore",
    "Norman",
    "Oklahoma City",
    "Stillwater",
    "Tulsa"
  ],
  "OR": [
    "Albany",
    "Beaverton",
    "Bend",
    "Corvallis",
    "Eugene",
    "Gresham",
    "Hillsboro",
    "Keizer",
    "Lake Oswego",
    "Medford",
    "Portland",
    "Salem",
    "Springfield",
    "Tigard"
  ],
  "PA": [
    "Allentown",
    "Altoona",
    "Bethlehem",
    "Erie",
    "Harrisburg",
    "Lancaster",
    "Philadelphia",
    "Pittsburgh",
    "Reading",
    "Scranton",
    "State College",
    "Wilkes-Barre",
    "York"
  ],
  "RI": [
    "Cranston",
    "East Providence",
    "Pawtucket",
    "Providence",
    "Warwick",
    "Woonsocket"
  ],
  "SC": [
    "Charleston",
    "Columbia",
    "Florence",
    "Goose Creek",
    "Greenville",
    "Hilton Head Island",
    "Mount Pleasant",
    "North Charleston",
    "Rock Hill",
    "Spartanburg",
    "Summerville",
    "Sumter"
  ],
  "SD": ["Rapid City", "Sioux Falls"],
  "TN": [
    "Bartlett",
    "Brentwood",
    "Chattanooga",
    "Clarksville",
    "Cleveland",
    "Collierville",
    "Franklin",
    "Germantown",
    "Hendersonville",
    "Jackson",
    "Johnson City",
    "Kingsport",
    "Knoxville",
    "Memphis",
    "Murfreesboro",
    "Nashville",
    "Smyrna"
  ],
  "TX": [
    "Abilene",
    "Allen",
    "Amarillo",
    "Arlington",
    "Austin",
    "Baytown",
    "Beaumont",
    "Brownsville",
    "Carrollton",
    "Cedar Park",
    "College Station",
    "Conroe",
    "Corpus Christi",
    "Dallas",
    "Denton",
    "Edinburg",
    "El Paso",
    "Euless",
    "Flower Mound",
    "Fort Worth",
    "Frisco",
    "Garland",
    "Grand Prairie",
    "Harlingen",
    "Houston",
    "Irving",
    "Killeen",
    "Laredo",
    "League City",
    "Lewisville",
    "Longview",
    "Lubbock",
    "McAllen",
    "McKinney",
    "Mesquite",
    "Midland",
    "Mission",
    "Missouri City",
    "New Braunfels",
    "North Richland Hills",
    "Odessa",
    "Pasadena",
    "Pearland",
    "Pflugerville",
    "Pharr",
    "Plano",
    "Richardson",
    "Round Rock",
    "Rowlett",
    "San Angelo",
    "San Antonio",
    "Sugar Land",
    "Temple",
    "Tyler",
    "Victoria",
    "Waco",
    "Wichita Falls"
  ],
  "UT": [
    "Bountiful",
    "Draper",
    "Layton",
    "Lehi",
    "Logan",
    "Murray",
    "Ogden",
    "Orem",
    "Provo",
    "Riverton",
    "Roy",
    "Salt Lake City",
    "Sandy",
    "South Jordan",
    "St. George",
    "Taylorsville",
    "West Jordan",
    "West Valley City"
  ],
  "VA": [
    "Alexandria",
    "Arlington",
    "Chesapeake",
    "Hampton",
    "Lynchburg",
    "Newport News",
    "Norfolk",
    "Portsmouth",
    "Richmond",
    "Roanoke",
    "Suffolk",
    "Virginia Beach"
  ],
  "VT": ["Burlington"],
  "WA": [
    "Auburn",
    "Bellevue",
    "Bellingham",
    "Everett",
    "Federal Way",
    "Kennewick",
    "Kent",
    "Kirkland",
    "Lakewood",
    "Marysville",
    "Olympia",
    "Pasco",
    "Redmond",
    "Renton",
    "Richland",
    "Sammamish",
    "Seattle",
    "Spokane",
    "Spokane Valley",
    "Tacoma",
    "Vancouver",
    "Yakima"
  ],
  "WI": [
    "Appleton",
    "Eau Claire",
    "Green Bay",
    "Janesville",
    "Kenosha",
    "La Crosse",
    "Madison",
    "Milwaukee",
    "Oshkosh",
    "Racine",
    "Waukesha",
    "West Allis"
  ],
  "WV": ["Charleston", "Huntington"],
  "WY": ["Casper", "Cheyenne"]
}